### ISSUE TITLE
'EMSDKFull.h' file not found

### ISSUE THREAD

**Issue by fengguixian** [easemob/sdk-ios-cocoapods-integration#12]
因为ipv6的原因更新sdk,但是运行出很多错呀，如题是一个；
[[EaseMob sharedInstance].chatManager stopPlayingAudio], 这个stop函数没有了？

**Comment by fengguixian** [comment]
人在么？求解答，很着急的，适配ipv6，等着上线啊

**Comment by Neil-Cao** [comment]
你是从什么版本升上来的？现在播放音频的控制都放到EaseUI EMCDDeviceManager了，有方法- (void)stopPlaying;


在 2016年6月29日，上午9:39，fengguixian <notifications@github.com<mailto:notifications@github.com>> 写道：


人在么？求解答，很着急的，适配ipv6，等着上线啊

**Comment by fengguixian** [comment]
从2.1.4，想升到2.2.5

**Comment by Neil-Cao** [comment]
原来在SDK的一些方法提取出来开源了 在EMCDDeviceManager里面

在 2016年6月29日，上午10:05，fengguixian <notifications@github.com<mailto:notifications@github.com>> 写道：


从2.1.4，想升到2.2.5

**Comment by fengguixian** [comment]
我搜索你sdk都没找到这个方法啊，是不是这sdk包有问题？

**Comment by Neil-Cao** [comment]
没有在sdk里，你从官网下载sdk或者直接去github：https://github.com/easemob/easeui_ios/tree/dev

在 2016年6月29日，上午10:14，fengguixian <notifications@github.com<mailto:notifications@github.com>> 写道：


我搜索你sdk都没找到这个方法啊，是不是这sdk包有问题？

**Comment by fengguixian** [comment]
那个提示这个EMSDKFull没有呢？

**Comment by lizilong1989** [comment]
@fengguixian 直接用EaseMob.h吧,EMSDKFull在之前版本已经删除了

**Comment by fengguixian** [comment]
你们的lib是支持arm64的吗？改了好多东西，终于代码不报错了，但是编译报错；
还有一个问题，现在如果需要切换耳机或者外音模式该在哪里切换？原来的函数好像没了

**Comment by fengguixian** [comment]
@lizilong1989

**Comment by lizilong1989** [comment]
@fengguixian sdk支持arm64

**Comment by lizilong1989** [comment]
@fengguixian 你指的实时语音通话,还是语音消息播放?

**Comment by lizilong1989** [comment]
@fengguixian 语音播放都已经从sdk移出去了,你可在官网上下载最新的Demo, http://downloads.easemob.com/downloads/ios-easemob-sdk-2.2.6.zip
下载解压后,在语音播放相关的code在EaseUI/EMUIKit/3rdparty/DeviceHelper路径下

**Comment by fengguixian** [comment]
@lizilong1989 在么？？我已经更新到了2.2.6版本，提交给苹果审核，但是苹果那边出现连接不到服务器的问题，请问下，服务器在国外会不会出现这个连接不上的问题，还是说ipv6适配还是有问题？？很急额，app被打回来了。
